version: '2'
services:
  paquetero_integ:
    build: . 
    environment:
      - AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
      - AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
      - BUCKET=solr-indexer/solr-backup
      - IMAGE_UNDER_TEST=ericzumba/paquetero
      - SHARED_VOLUME=/tmp
      - SOLR_HOST=solr
    depends_on:
      - solr
    volumes:
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock  
      - ./features:/usr/app/features
  solr:
    build: solr 
    expose: 
      - "8983"
    ports: 
      - "8983:8983" 
    volumes:
      - /tmp:/tmp
