version: '2'
services:
  paquetero-integ:
    build: . 
    environment:
      - IMAGE_UNDER_TEST="ericzumba/paquetero"
      - AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
      - AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
    depends_on:
      - solr
    volumes_from:
      - solr
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
      - ./features:/usr/app/features
  solr:
    build: solr 
    expose: 
      - "8983"
    ports: 
      - "8983:8983" 
    volumes:
      - tmp:/tmp
volumes:
  tmp:
    external: false
